#!/bin/sh 
# ruta iconos /usr/share/icons/gnome/32x32/status
usuario=$(whoami)
source /home/$usuario/.bashrc
pid=$(pgrep -u $usuario lxsession | head -n 1)
dbus=$(grep -z DBUS_SESSION_BUS_ADDRESS /proc/$pid/environ | sed 's/DBUS_SESSION_BUS_ADDRESS=//' )
export DBUS_SESSION_BUS_ADDRESS=$dbus
export HOME=/home/$usuario
export DISPLAY=:0

porcentaje_carga_bat=$(cat /sys/class/power_supply/BAT0/capacity)
fuenteacdc=$(cat /sys/class/power_supply/BAT0/status)

if  [ $porcentaje_carga_bat -gt 90 ] && [ $fuenteacdc = "Full" ] ; then
    /usr/bin/notify-send --expire-time=10000 -i "battery-full-charged" 'Bateria Cargada!!!'
elif
    [ $porcentaje_carga_bat -lt 18 ] && [ $fuenteacdc = "Discharging" ] ; then
    /usr/bin/notify-send --expire-time=10000 -i "battery-caution" 'Bateria Descargada!!!' "$porcentaje_carga_bat%"
else
exit 0
fi



################ crontab #######################

* guardar script en /home/bateria.sh

* crear crontab asi:

MAILTO=""
*/1 * * * * sh /home/bateria.sh
